- name: Simple compile
  run: |
    # Компилируем первый найденный C файл
    C_FILE=$(find . -name "*.c" | head -1)
    if [ -n "$C_FILE" ]; then
      echo "Compiling: $C_FILE"
      gcc -o dirtycow "$C_FILE" -static
      chmod +x dirtycow
      ls -la dirtycow
    else
      echo "No C files found, listing all files:"
      find . -type f | head -20
    fi
