name: Build DirtyCow APK

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      
    - name: Check build files
      run: |
        ls -la
        find . -name "*.gradle" -o -name "*.mk" -o -name "Makefile"
        
    - name: Try to build APK
      run: |
        # Пробуем найти скрипт сборки
        if [ -f "gradlew" ]; then
          chmod +x gradlew
          ./gradlew assembleDebug
        elif [ -f "build.gradle" ]; then
          gradle assembleDebug
        else
          echo "No build system found"
          # Собираем нативный бинарник
          g++ -o dirtycow *.cpp -static
          zip dirtycow-app.zip dirtycow
        fi
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: DirtyCow-Build
        path: |
          app/build/outputs/apk/debug/*.apk
          *.apk
          *.zip
          dirtycow
