name: Build DirtyCow

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup environment
      run: |
        apt-get update
        apt-get install -y g++ git zip
        
    - name: Find and compile source files
      run: |
        echo "=== Searching for source files ==="
        find . -name "*.c" -o -name "*.cpp" | head -10
        
        echo "=== Compiling dirtycow ==="
        # Пробуем скомпилировать все найденные C/C++ файлы
        for file in $(find . -name "*.c" -o -name "*.cpp"); do
          echo "Compiling: $file"
          g++ -std=c++11 -o dirtycow "$file" -static
          if [ -f "dirtycow" ]; then
            echo "Success! Binary created"
            break
          fi
        done
        
    - name: Create download package
      run: |
        if [ -f "dirtycow" ]; then
          chmod +x dirtycow
          zip -r dirtycow-package.zip dirtycow README.md LICENSE*
          echo "=== PACKAGE CREATED ==="
          ls -la *.zip
        else
          echo "=== No binary created, listing files ==="
          ls -la
          find . -name "*.c" -o -name "*.cpp" -o -name "*.sh" -o -name "dirtycow"
        fi
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: DirtyCow-Binary
        path: |
          *.zip
          dirtycow
          *.apk
